# Generated by Django 3.2.7 on 2021-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=80)),
                ('content', models.TextField()),
            ],
        ),
    ]
